retrieval:
    entities:
    - entity: organizations
      #outputCsv: c:/tmp/orgs_data_2012_2013.csv
      #outputCsv: c:/tmp/orgs_data_2013_2014.csv
      #outputCsv: c:/tmp/orgs_data_2014_2015.csv
      #outputCsv: c:/tmp/orgs_data_2015_2016.csv
      outputCsv: c:/tmp/orgs_data_2016_2017.csv
      urls: rfetm_league_qualifications_urls.yaml
      #seasons: 2012-2013
      #seasons: 2013-2014
      #seasons: 2014-2015
      #seasons: 2015-2016
      seasons: 2016-2017
    - entity: players
      outputCsv:
      urls:
      seasons: